---

language: python
services: docker

env:
  global:
    - ROLE_NAME: f5_atc_deploy_declaration
  matrix:
    - MOLECULE_DISTRO: centos7
      MOLECULE_DOCKER_COMMAND: /usr/lib/systemd/systemd
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian9

install:
  # Install test dependencies.
  - pip install molecule docker yamllint flake8 ansible-lint

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME f5devcentral.$ROLE_NAME
  - cd f5devcentral.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
